## What is TensorFlow?
TensorFlow is a general purpose machine learning library. Can also make use of a distributed system (i.e. Multiple CPU, GPU and etc)

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.13.1'

In [3]:
# Declaring a TensorFlow operation
c = tf.constant('Hello World')

In [4]:
# Executing the TensorFlow operation
with tf.Session() as sess:
    print(sess.run(c))

b'Hello World'


In [5]:
# Always reset the graph as there could be alteratiosn
tf.reset_default_graph()

In [6]:
hello_world = tf.constant('Helloworld!!!')

In [7]:
# Alternative way of executing TensorFlow without using 'with'
sess = tf.Session()
sess.run(hello_world)

b'Helloworld!!!'

In [8]:
tf.reset_default_graph()

In [9]:
h = tf.constant('Hello')

In [10]:
w = tf.constant('World')

In [11]:
hw = h + w

In [12]:
h

<tf.Tensor 'Const:0' shape=() dtype=string>

In [13]:
w

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [14]:
hw

<tf.Tensor 'add:0' shape=() dtype=string>

Variables 'h' and 'w' are both Tf constant of type string and hw is the first 'add' operation

In [15]:
with tf.Session() as sess:
    print(sess.run(hw)) # Identical to 'h+w'

b'HelloWorld'


# Basic Concepts

A Tensor of Order: <br>
0 -> Scalar -> 1 <br>
1 -> Vector -> [1,2,3,4] <br>
2 -> Matrix -> [1,2,3,4; 5,6,7,8] <br>
<br>
Graph: Nodes and Edges

In [16]:
x = tf.constant(7.0)

In [17]:
x

<tf.Tensor 'Const_2:0' shape=() dtype=float32>

In [18]:
y = tf.Variable(7.2)

Instructions for updating:
Colocations handled automatically by placer.


In [19]:
y

<tf.Variable 'Variable:0' shape=() dtype=float32_ref>

In [20]:
y = y.assign(5)

In [21]:
y

<tf.Tensor 'Assign:0' shape=() dtype=float32_ref>

In [22]:
with tf.Session() as sess:
    initialization = tf.global_variables_initializer() # Must call initializers
    print(y.eval())

5.0


In [23]:
tf.reset_default_graph()

In [24]:
g = tf.Graph()

In [25]:
with g.as_default():
    x = tf.Variable(2, name='x_2')
    y = tf.Variable(3, name='y_3')
    sum_op = tf.add(x, y, name='x_y_add')
    
    with tf.Session() as sess:
        initialization = tf.global_variables_initializer()
        sess.run(initialization)
        print(sum_op.eval())

5


In [26]:
vect = tf.constant([1, 2, 3, 4, 5, 6, 7])

In [27]:
ones = tf.ones([7], dtype=tf.int32)

In [28]:
vec_add = tf.add(vect, ones)

In [29]:
with tf.Session() as sess:
    add_vec = vec_add.eval()

In [30]:
add_vec

array([2, 3, 4, 5, 6, 7, 8])

In [31]:
scalar = tf.zeros([0])

In [32]:
vec = tf.zeros([1])

In [33]:
mat = tf.zeros([2,3])

In [34]:
# Tensorflow automatically does broadcasting (Makes both dimensions as the same and adds them up)
vect = tf.constant([1, 2, 3, 4, 5, 6, 7])
ones = tf.constant(1, dtype=tf.int32)
vec_add = tf.add(vect, ones)
with tf.Session() as sess:
    add_vec = vec_add.eval()
add_vec

array([2, 3, 4, 5, 6, 7, 8])

In [35]:
tf.reset_default_graph()

In [36]:
v_1 = tf.constant([[1,2,3], [4,5,6], [7,8,9]])

In [37]:
v_2 = tf.constant([[4,5], [4,5], [4,5]])

In [38]:
r_mul = tf.matmul(v_1, v_2)

In [39]:
with tf.Session() as sess:
    print(r_mul.eval()) # I don't get how this works...

[[ 24  30]
 [ 60  75]
 [ 96 120]]


In [40]:
tf.reset_default_graph()

In [52]:
x = tf.Variable(10)

In [53]:
y = tf.Variable(12)

In [54]:
z = x*y + 100

In [44]:
sess = tf.Session()

In [45]:
sess.run(x.initializer)

In [46]:
sess.run(y.initializer)

In [47]:
sess.run(z)

220

In [48]:
sess.close()

In [49]:
tf.reset_default_graph()

In [60]:
# Redefine the variables after manipulation and etc
x = tf.Variable(10)
y = tf.Variable(12)
z = x*y+100
init = tf.global_variables_initializer()

In [61]:
# Alternative method of running the session
with tf.Session() as sess:
    init.run()
    f = z.eval()

In [62]:
f

220

In [63]:
tf.reset_default_graph()

In [72]:
sess = tf.InteractiveSession()

D:\ProgramData\Anaconda3\envs\TensorFlow-3.6\lib\site-packages\tensorflow\python\client\session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [77]:
x = tf.constant(2)
x.get_shape()

TensorShape([])

In [78]:
ph = tf.placeholder(tf.float64, s)

In [79]:
ph

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float64>

# Eager-Mode
Eager-Mode enables the easy access to data rather than running Sessions <br>
(Restart Kernel)

In [1]:
import tensorflow as tf

In [2]:
tf.enable_eager_execution()

In [3]:
tf.executing_eagerly()

True

In [4]:
a = tf.constant(2)

In [6]:
print(a)

tf.Tensor(2, shape=(), dtype=int32)


In [7]:
b = tf.constant(3)

In [8]:
c = a + b

In [9]:
print(c)

tf.Tensor(5, shape=(), dtype=int32)


In [10]:
print(a*b)

tf.Tensor(6, shape=(), dtype=int32)


In [12]:
import numpy as np

In [19]:
a = np.array([[1,2], [3,4]], dtype=np.float32)

In [20]:
b = tf.constant([[5,6], [7,9]], dtype=tf.float32)

In [21]:
c = tf.matmul(a,b)

In [22]:
c

<tf.Tensor: id=11, shape=(2, 2), dtype=float32, numpy=
array([[19., 24.],
       [43., 54.]], dtype=float32)>